package gui;

import console.AbstractUser;
import console.DataProcessing;

import console.Doc;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.*;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Locale;

public class FileManagerFrame {
    AbstractUser user;
    FileSelectJudgeFrame fileSelectJudgeFrame;
    FileBrowsingFrame fileBrowsingFrame;

    private JPanel fileManagerPanel;
    private JFileChooser fileChooser;
    private JLabel selectedFileLabel;
    private JPanel selectedLabelPanel;
    private JButton selectFileButton;
    private JPanel selectFileButtonPanel;

    String NumberInFileManagerFrame;
    String DescriptionInFileManagerFrame;

    FileManagerFrame(FileBrowsingFrame fileBrowsingFrame) {
        this.fileBrowsingFrame = fileBrowsingFrame;

        $$$setupUI$$$();

        fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setMultiSelectionEnabled(false);

        selectFileButton.addActionListener(e -> {
            try {
                fileSelectJudgeFrame = new FileSelectJudgeFrame(this);
                fileSelectJudgeFrame.FileSelectFrameShow();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });


    }

    // 新增方法用于设置用户
    public void setUser(AbstractUser user) {
        this.user = user;
    }


    public JPanel getFileManagerPanel() {
        return fileManagerPanel;
    }

    public boolean uploadFile(File selectedFile) throws SQLException, IOException {
        //boolean result=false;

        if (selectedFile == null || !selectedFile.exists()) {
            System.out.println("File does not exist!");
            return false;
        }

        byte[] buffer = new byte[1024];

        try {
            Doc doc = DataProcessing.searchDoc(NumberInFileManagerFrame);
            String uploadpath = "D:\\@Java\\Object-oriented and multithreaded comprehensive experiment\\Manager System\\uploadfile\\";
            if (doc == null) {
                Timestamp timestamp = new Timestamp(System.currentTimeMillis());

                BufferedInputStream infile = new BufferedInputStream(new FileInputStream(selectedFile.getAbsolutePath()));
                BufferedOutputStream targetfile = new BufferedOutputStream(new FileOutputStream(uploadpath + selectedFile.getName()));
                while (true) {
                    int byteRead = infile.read(buffer);
                    if (byteRead == -1) {
                        break;
                    }
                    targetfile.write(buffer, 0, byteRead);
                }

                infile.close();
                targetfile.close();
                DataProcessing.insertDoc(NumberInFileManagerFrame, fileBrowsingFrame.mainFrame.user.getName(), timestamp, DescriptionInFileManagerFrame, selectedFile.getName());

                new DownAndUpLoadSuccess();
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "Having the same id", "The Same!", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        } catch (SQLException | IOException e) {
            e.printStackTrace();
            throw e;
        }
    }

    /**
     * Method generated by IntelliJ IDEA gui Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        fileManagerPanel = new JPanel();
        fileManagerPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 5, 0), -1, -1));
        fileManagerPanel.setAlignmentX(1.0f);
        fileManagerPanel.setAlignmentY(1.0f);
        fileManagerPanel.setAutoscrolls(false);
        Font fileManagerPanelFont = this.$$$getFont$$$(null, -1, -1, fileManagerPanel.getFont());
        if (fileManagerPanelFont != null) fileManagerPanel.setFont(fileManagerPanelFont);
        selectedLabelPanel = new JPanel();
        selectedLabelPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        fileManagerPanel.add(selectedLabelPanel, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        selectedFileLabel = new JLabel();
        selectedFileLabel.setAlignmentX(1.0f);
        selectedFileLabel.setAlignmentY(1.0f);
        selectedFileLabel.setAutoscrolls(false);
        Font selectedFileLabelFont = this.$$$getFont$$$("Century Schoolbook", -1, -1, selectedFileLabel.getFont());
        if (selectedFileLabelFont != null) selectedFileLabel.setFont(selectedFileLabelFont);
        selectedFileLabel.setText("No file selected");
        selectedLabelPanel.add(selectedFileLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(20, -1), null, 0, false));
        selectFileButtonPanel = new JPanel();
        selectFileButtonPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        fileManagerPanel.add(selectFileButtonPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        selectFileButton = new JButton();
        selectFileButton.setActionCommand("selectFileButton");
        selectFileButton.setLabel("select File");
        selectFileButton.setText("select File");
        selectFileButtonPanel.add(selectFileButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fileManagerPanel;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JLabel getSelectedFileLabel() {
        return selectedFileLabel;
    }
}
